error: X(1, 2)

Traceback (most recent call last):
ak-runner
value = fn(*args, **kw)
File "main.py", line 15, in main
callstuff()

ak-runner
return self.runner.call_in_activity(func, args, kw)
-- main.py main --
from autokitteh import activity


class X(Exception):
    def __init__(self, a, b):
        self._a, self._b = a, b
        super().__init__(a, b)

@activity
def callstuff():
    raise X(1, 2)


def main(_):
    callstuff()
